import { defaultSchema } from "rehype-sanitize";

// Class names added by remark-gfm for task lists
export const TASK_LIST_CLASS = "contains-task-list";
export const TASK_LIST_ITEM_CLASS = "task-list-item";

// Timeline content uses text-[15px] leading-5 (20px line-height).
const ROW_HEIGHT_PX = 20;

// Compact mode display settings — fold only after ~250 characters, show a similar-length preview.
export const COMPACT_MODE_CONFIG = {
  previewRows: 10, // collapsed preview height (~250 chars at ~25/line)
  triggerRows: 13, // only fold when content is taller than this
  minContentLength: 250, // never fold memos at or under this length
  gradientHeight: "h-10", // fade overlay above the "Show more" link
} as const;

// Height the collapsed preview is clamped to, in pixels.
export const getPreviewMaxHeightPx = () => COMPACT_MODE_CONFIG.previewRows * ROW_HEIGHT_PX;

// Height a memo must exceed before it gets folded at all, in pixels.
export const getCompactTriggerHeightPx = () => COMPACT_MODE_CONFIG.triggerRows * ROW_HEIGHT_PX;

// Whether content of the given rendered height should be collapsed. Kept pure for unit testing.
export const shouldCompactContent = (contentHeightPx: number, triggerHeightPx: number) => contentHeightPx > triggerHeightPx;

/** True when plain-text length is past the fold floor. */
export const isPastCompactContentFloor = (content: string): boolean =>
  content.trim().length > COMPACT_MODE_CONFIG.minContentLength;

/** Fallback when DOM height is unavailable (common on mobile before layout settles). */
export const estimateContentNeedsCompact = (content: string): boolean => {
  const normalized = content.trim();
  if (!isPastCompactContentFloor(normalized)) {
    return false;
  }

  const lineCount = normalized.split(/\r?\n/).length;
  if (lineCount > COMPACT_MODE_CONFIG.triggerRows) {
    return true;
  }

  // Roughly 28 characters per line on a narrow phone screen.
  return normalized.length > COMPACT_MODE_CONFIG.triggerRows * 28;
};

export const COMPACT_STATES: Record<"ALL" | "SNIPPET", { textKey: string; next: "ALL" | "SNIPPET" }> = {
  ALL: { textKey: "layout.show-more", next: "SNIPPET" },
  SNIPPET: { textKey: "layout.show-less", next: "ALL" },
};

const TRUSTED_IFRAME_SRC_PATTERNS = [
  /^https:\/\/www\.youtube\.com\/embed\/[^?#]+(?:\?.*)?$/i,
  /^https:\/\/www\.youtube-nocookie\.com\/embed\/[^?#]+(?:\?.*)?$/i,
  /^https:\/\/player\.vimeo\.com\/video\/[^?#]+(?:\?.*)?$/i,
  /^https:\/\/open\.spotify\.com\/embed\/[^?#]+(?:\?.*)?$/i,
  /^https:\/\/w\.soundcloud\.com\/player\/?(?:\?.*)?$/i,
  /^https:\/\/www\.loom\.com\/embed\/[^?#]+(?:\?.*)?$/i,
  /^https:\/\/www\.google\.com\/maps\/embed(?:\/[^?#]*)?(?:\?.*)?$/i,
  /^https:\/\/(?:app\.)?diagrams\.net\/(?:[^?#]+)?(?:\?.*)?$/i,
  /^https:\/\/(?:www\.)?draw\.io\/(?:[^?#]+)?(?:\?.*)?$/i,
];

const KATEX_INLINE_CLASS_NAMES = ["language-math", "math-inline"] as const;
const KATEX_BLOCK_CLASS_NAMES = ["language-math", "math-display"] as const;
const SPAN_CLASS_NAMES = ["mention", "tag"] as const;
const INPUT_ATTRIBUTES = [...(defaultSchema.attributes?.input || []), ["checked", true]] as const;

export const isTrustedIframeSrc = (src: string): boolean => TRUSTED_IFRAME_SRC_PATTERNS.some((pattern) => pattern.test(src));

/**
 * Sanitization schema for markdown HTML content.
 * Extends the default schema to allow:
 * - KaTeX marker classes used before trusted KaTeX rendering runs
 * - Mention/tag metadata generated by trusted remark plugins
 * - iframe embeds only from trusted video providers
 *
 * This prevents XSS attacks while preserving math rendering functionality.
 */
export const SANITIZE_SCHEMA = {
  ...defaultSchema,
  attributes: {
    ...defaultSchema.attributes,
    img: [...(defaultSchema.attributes?.img || []), "height", "width"],
    input: INPUT_ATTRIBUTES,
    code: [...(defaultSchema.attributes?.code || []), ["className", ...KATEX_INLINE_CLASS_NAMES, ...KATEX_BLOCK_CLASS_NAMES]],
    span: [...(defaultSchema.attributes?.span || []), ["className", ...SPAN_CLASS_NAMES], ["aria*"], ["data*"]],
    iframe: [
      ["src", ...TRUSTED_IFRAME_SRC_PATTERNS],
      "width",
      "height",
      "frameborder",
      "allowfullscreen",
      "allow",
      "title",
      "referrerpolicy",
      "loading",
    ],
  },
  tagNames: [...(defaultSchema.tagNames || []), "iframe"],
  protocols: {
    ...defaultSchema.protocols,
    src: ["https"],
  },
};
