name: memos

services:
  memos:
    build:
      context: .
      dockerfile: scripts/Dockerfile.production
      args:
        VERSION: ${MEMOS_VERSION:-dev}
        COMMIT: ${MEMOS_COMMIT:-local}
    image: gchongo/memos:local
    container_name: memos
    restart: unless-stopped
    ports:
      - "${MEMOS_PORT:-5230}:5230"
    volumes:
      - ./data:/var/opt/memos
    environment:
      TZ: ${TZ:-Asia/Shanghai}
